### ISSUE TITLE
Any plan to make the JsonConfig to support customizing the date format of different Java date types?

### ISSUE THREAD

**Issue by hei1233212000** [eclipse-ee4j/jsonb-api#87]
In the JSON-B 1.0 specification, section 3.5, it supports ALL the native date types of Java like java.util.date, java.time.LocalDate and java.time.LocalTime. HOWEVER, in the [JsonConfig](https://github.com/javaee/jsonb-spec/blob/1.0/api/src/main/java/javax/json/bind/JsonbConfig.java), it ONLY provide a single withDateFormat() method (section 4.8) to apply the global custom date format which will make ALL supported date type to use this format.

BUT, there will be a problem if your application use different different date types such as java.util.Date, java.time.LocalDate and java.time.LocalTime. Because when you define the

> yyyy-MM-dd

in withDateFormat(), there will be an exception thrown if the object has java.time.LocalTime field.

So, I think it maybe better to allow the client to configure the date format by different date type => e.g:

- withDateFormat(java.util.Date, dateFormat, Locale)
- withDateFormat(java.time.LocalDate, dateFormat, Locale)
- ...

What do you think about it?
Thank you.

**Comment by aguibert** [comment]
This is something we could consider for the next version of the spec. However, there are workarounds to this available with 1.0.

Here are some examples of existing behavior...

Default config w/ dateFormat of `yyyy-MM-dd`:
```java
        LocalDate date = LocalDate.of(2016, 11, 10);
        System.out.println(jsonb.toJson(date));

        java.util.Date julDate = Date.from(Instant.now());
        System.out.println(jsonb.toJson(julDate));

        LocalDateTime dateTime = LocalDateTime.now();
        System.out.println(jsonb.toJson(dateTime));
```
Produces:
```
"2019-07-22"
"2019-07-22"
"2019-07-22" // time precision is lost here
```

If a time field is added to the date format: `

When we try to serialize a field without a time element such as `LocalDate`, we get the following error (in Yasson at least)
```
Exception in thread "main" javax.json.bind.JsonbException: Internal error: Unsupported field: HourOfDay
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:82)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:102)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:118)
	at atest.AGGMain.main(AGGMain.java:63)
Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: HourOfDay
	at java.time.LocalDate.get0(LocalDate.java:680)
	at java.time.LocalDate.getLong(LocalDate.java:659)
	at java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:298)
	at java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2540)
	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179)
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
	at org.eclipse.yasson.internal.serializer.AbstractDateTimeSerializer.formatWithFormatter(AbstractDateTimeSerializer.java:135)
	at org.eclipse.yasson.internal.serializer.AbstractDateTimeSerializer.toJson(AbstractDateTimeSerializer.java:67)
	at org.eclipse.yasson.internal.serializer.AbstractDateTimeSerializer.serialize(AbstractDateTimeSerializer.java:52)
	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:148)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:76)
	... 3 more
```

A workaround that can be done for now is to specify optional elements with the time format:
`withTimeFormat("yyyy-MM-dd['T'HH:mm:ss]")`

With the original code example, we get the output:
```
"2019-07-22"
"2019-07-22T19:50:02"
"2019-07-22T14:50:02"
```

**Comment by rmannibucau** [comment]
Hi @aguibert ,

Think the defaults should be toString/parse of each type to ensure it fits well each potential date/time/timezone formatting properly.

The question of the scope of JsonbConfig.DATE_FORMAT is real and, I think we could add JsonbConfig.DATETIME_FORMAT, JsonbConfig.TIME_FORMAT and JsonbConfig.ZONEDDATETIME_FORMAT to ensure we cover them all.

However, it brings a question: how do you make a date looking like a datetime (it regularly happens you want a complete format with 00:00:00 even if not present in memory). With a fake pattern?

Open thought: this is where we can wait a minute and think about the API direction IMHO: everything is doable with an adapter so we might just provide default adapters (through the SPI to ensure there is no "impl" in the API) and let the user configure the right adapter when needed, either globally or not. The date adapter - taking a DateTimeFormatter could be created from the config probably. This would limit the number of properties and enable more flexibility since the user can finelly tune for which type what it does. You can also think about the need of anything in the API since this kind of adapter is trivial, so it is really about how defaults work more than anything else IMHO. For me, defaults are really about iso-8601 only so what about fully aligning on it - as a target?


Romain

**Comment by aguibert** [comment]
I think we could add the following methods:
```
withDateTimeFormat(String dateFormat, Locale locale)
withZonedDateTimeFormat(String dateFormat, Locale locale)
```

So given a particular time-based object (e.g. java.util.Date, LocalDate, LocalDateTime, ZonedDateTime, etc), the formatting would be applied according to the following rules:
1. If object being serialized is an instanceof ZonedDateTime, use the `withZonedDateTime` format, if set
1. If object being serialized is an instanceof ZonedDateTime or DateTime, use the `withDateTimeFormat`, if set
1. If object being serialized is any time-based object, use `withDateFormat`, if set
1. Otherwise, no formatting has been requested so use defaults

**Comment by rmannibucau** [comment]
Sounds good to fix that issue which has some previous broken config.

**Comment by artooksanen** [comment]
Has there been any progress in this? This is needed when serving many java objects on a restservice and these objects contain both java.sql.Timestamp and java.sql.Date fields. In the old JEE7 implementation Timestamps are integers and Dates are formatted strings on the JSON output. There are many clients that expect that the format is still the same. Using JsonbConfig.DATE_FORMAT the format can be set, but then the same applies to both types.
